### PR TITLE
Add project name, version and added skipped scenario functionality

### PR DESCRIPTION
**Pull request by trinidad8516**
Added Skipped test scenarios and functionality to the summary template file and project name and version.

### CODE REVIEW

**Comment by tilmanginzel** [comment]
Hey @trinidad8516, thanks for the pull request! These are nice improvements, I will test and merge them in the coming days and release a new version. :)

Do we need the `com.energizedwork.idea-*` gradle plugins?

**Comment by trinidad8516** [comment]
Hey @tilmanginzel, May be not the .idea ones let me test them and look at the documentation for the plugin.

**Comment by trinidad8516** [comment]
@tilmanginzel I made the changes and I did more testing please feel free to do test and review some more.

**Comment by trinidad8516** [comment]
Sure that works, I’ll send the changes

**Comment by trinidad8516** [comment]
@tilmanginzel I made the changes that you suggested.

**Comment by trinidad8516** [comment]
@tilmanginzel I found a little bug, I am going to fix it and also add a scenario.

**Comment by tilmanginzel** [comment]
Perfect, thank you! 👍 If you want and the bug is not related to these changes, I could already merge them.

**Comment by trinidad8516** [comment]
@tilmanginzel fixed, please merge when you can!

**Comment by tilmanginzel** [comment]
Hi @trinidad8516, I have added another small commit, I hope you don't mind :)
* There was still a minor issue that the PassSkipTestSpec was shown as skipped in the table
* I removed the background color and instead only made the text lightgray

The commits have been merged. Thanks again for the effort! 👍 I will release a new version 0.2.1 as soon as possible.

**Comment by tilmanginzel** [comment]
I just published version v0.2.1 with all the changes. :)

**Pull request merged**
